require('dotenv').config();
const express = require('express');
const cors = require('cors');
const healthRoutes = require('./routes/health');
const app = express();
const PORT = process.env.PORT || 3000;
app.use(cors());
app.use(express.json());
app.use('/api', healthRoutes);
app.listen(PORT, () => { console.log(`🚀 Server running on port ${PORT}`); });
