#!/usr/bin/python3

import os
import pathlib
import sys
from rich import print
from rich.filesize import decimal
from rich.markup import escape
from rich.text import Text
from rich.tree import Tree

def walk_directory(directory: pathlib.Path, tree: Tree) -> tuple:
    """Recursively build a Tree with directory contents and count folders and files."""
    num_folders = 0
    num_files = 0

    try:
        for path in directory.iterdir():
            # Ignore hidden files
            if path.name.startswith(".") or path.parts[-1].startswith("."):
                continue

            if path.is_dir():
                num_folders += 1
                style = "dim" if path.name.startswith("__") else ""
                branch = tree.add(
                    f"[bold magenta]:open_file_folder: [link file://{path}]{escape(path.name)}",
                    style=style,
                    guide_style=style,
                )
                sub_folders, sub_files = walk_directory(path, branch)  # Recursive call
                num_folders += sub_folders
                num_files += sub_files
            else:
                num_files += 1
                text_filename = Text(path.name, "green")
                text_filename.highlight_regex(r"\..*$", "bold red")
                text_filename.stylize(f"link file://{path}")
                file_size = path.stat().st_size
                text_filename.append(f" ({decimal(file_size)})", "blue")
                icon = " " if path.suffix == ".py" else " "
                tree.add(Text(icon) + text_filename)
    except PermissionError:
        pass  # Skip directories without permission

    return num_folders, num_files

def main():
    try:
        directory = pathlib.Path(sys.argv[1]).resolve()
    except IndexError:
        directory = pathlib.Path(".").resolve()

    tree = Tree(
        f":open_file_folder: [link file://{directory}]{directory}",
        guide_style="bold bright_blue",
    )
    num_folders, num_files = walk_directory(directory, tree)
    print(tree)
    print(f"\n[bold]Total folders:[/bold] {num_folders}")
    print(f"[bold]Total files:[/bold] {num_files}")

if __name__ == "__main__":
    main()
